my_dbt_trino_project:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: minio
      database: datalake
      host: localhost
      port: 8080
      schema: analytics
      threads: 1